### PR TITLE
Adds support for Waterfox

### PR DESCRIPTION
**Pull request by zun1uwu**
This pull adds support for Waterfox and fixes a typo.
I think this pull is a good idea because more people are protected that way.

### CODE REVIEW

**Comment by AdvDebug** [comment]
i was gonna add Waterfox but the problem is that it's not signed, so i can't do that as it would make new bypasses.

**Comment by AdvDebug** [comment]
wait... nvm, my bad. waterfox binaries are signed, that's a problem from my part as i was making a program that modifies explorer memory (personal tool) that showed Waterfox as not signed.

**Comment by zun1uwu** [comment]
I understand, perhaps I should have investigated that.

**Comment by AdvDebug** [comment]
i'm clumsy sometimes, sorry

**Comment by zun1uwu** [comment]
No problem!

**Pull request merged**
